apiVersion: v1
entries:
  gmaas-github-api:
  - apiVersion: v2
    appVersion: 1.0.1
    created: "2023-01-11T23:55:20.007343661Z"
    description: An API developed in Python/Flask, its purpose is to extract some
      useful information from the GitHub API.
    digest: 718af021aacb8235b7ec4e6c81d931344733dce5381f163a1d07ee2574ebe470
    name: gmaas-github-api
    type: application
    urls:
    - https://guilhermemaas.github.io/gmaas-github-api/charts/gmaas-github-api-1.0.1.tgz
    version: 1.0.1
generated: "2023-01-11T23:55:20.005971067Z"
